deploy: jar 파일 생성여부 확인

diff --git a/.github/workflows/docker-push-deploy.yml b/.github/workflows/docker-push-deploy.yml
--- a/.github/workflows/docker-push-deploy.yml
+++ b/.github/workflows/docker-push-deploy.yml
@@ -27,6 +27,13 @@ jobs:
       - name: Build with Gradle
         run: ./gradlew build
 
+      - name: Check if JAR file exists
+        run: |
+          if [ ! -f build/libs/knutoyproject.jar ]; then
+          echo "JAR file not found!"
+          exit 1
+          fi
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
